const fs = require('fs');

const breedsEn = {
    1: {
        "history": "Believed to have originated on the Mediterranean island of Malta, the Maltese is a toy breed boasting a history of over 3,000 years. As a classic 'lap dog,' they monopolized the affection of noble ladies since the Roman Empire. Initially, they served to catch mice on sailing ships, but their beautiful appearance and elegant posture gradually made them precious gifts among European royalty. Bred purely for companionship over centuries, the Maltese with its white, silky coat has exceptional emotional resonance with humans, becoming one of the most beloved dogs.",
        "personality": "Though small, the Maltese is bold and brave. Deeply affectionate toward their families, they love sticking close to their owners and overflow with charm. They are highly perceptive and read their owner's emotional changes well, but they also have strong pride and stubbornness, often barking sharply or whining to get their way. They show a strong attachment to their territory and belongings, occasionally revealing their Terrier-like temperament by standing confidently against strangers or large dogs. Therefore, firm and consistent socialization and etiquette training from an early age are essential.",
        "health": "The most critical genetic issue to watch for is 'patellar luxation.' This condition, where the knee bone dislocates, is common in small breeds, and the Maltese has a particularly high incidence rate due to their thin bones. Installing anti-slip mats indoors and restricting them from standing on their hind legs is mandatory. Additionally, tear stains can cause the fur around their eyes to turn red, so wiping their eyes daily with a dedicated cleanser and feeding them low-allergy food helps."
    },
    2: {
        "history": "Originally bred as water retrievers in Germany, the Poodle's name comes from the German word 'pudelin,' meaning to splash in the water. They later gained immense popularity in France, becoming the national dog. To prevent the dog from sinking while swimming but still protect vital organs from cold water, the unique 'Poodle clip' (leaving fur around the chest and joints) was developed. Today, they are categorized by size into Standard, Miniature, and Toy, and their supreme intelligence and non-shedding coat make them incredibly popular worldwide.",
        "personality": "Poodles rank second in intelligence among all dog breeds. They learn commands at an astonishing speed and have an exceptional ability to empathize with their owners. They are highly sociable and playful, getting along well with other animals and children. However, their high intelligence means they can easily pick up bad habits if not trained properly, and they may manipulate situations to their advantage. They are highly active, requiring sufficient daily exercise and mental stimulation (like nosework or training games) to prevent stress-induced destructive behaviors.",
        "health": "Their signature curly coat sheds very little but is highly prone to matting, requiring daily brushing and regular grooming. Because their ear canals are covered with fur and lack ventilation, they are susceptible to ear infections (otitis externa), making ear cleaning after baths a priority. Toy Poodles are also prone to patellar luxation and progressive retinal atrophy (PRA), so regular eye check-ups and joint care are highly recommended."
    },
    3: {
        "history": "The Pomeranian is a miniaturized descendant of large sled dogs from the Pomerania region (now part of Germany and Poland). Queen Victoria of the UK fell in love with a small Pomeranian in the late 19th century and actively bred them to the tiny, fluffy size we know today. Despite their small stature, they still carry the courageous and robust genes of their Arctic sled-pulling ancestors, which explains their thick double coat designed to withstand extreme cold.",
        "personality": "Pomeranians are lively, extroverted, and brimming with confidence. They are extremely loyal to their owners but tend to be wary of strangers, often making them excellent watchdogs. However, their sled-dog heritage gives them a 'big dog trapped in a small body' complex, meaning they won't back down from dogs much larger than themselves. They can be prone to excessive barking and possessiveness over food or toys, so early socialization and boundary-setting are crucial to prevent them from becoming overly aggressive or yappy.",
        "health": "The most common health issue is patellar luxation due to their delicate bone structure. Another significant concern is 'Alopecia X' (black skin disease), a condition where they lose their fur, especially after being shaved too closely. Therefore, clipping their double coat too short with clippers should be avoided; scissor cuts are recommended. Tracheal collapse is also common, so using a harness rather than a neck collar is strongly advised."
    },
    4: {
        "history": "The Bichon Frise, whose name translates to 'curly lap dog' in French, originated in the Mediterranean region. During the Renaissance, they were highly favored by the French and Spanish nobility, often depicted in royal portraits. They traveled with sailors as companion dogs, spreading their popularity across continents. Their cotton-candy-like appearance and cheerful disposition have made them a symbol of joy and comfort throughout history.",
        "personality": "Known for their incredibly cheerful and affectionate nature, the Bichon Frise is the epitome of a companion dog. They love being the center of attention and thrive on human interaction. They are generally very friendly with strangers, children, and other pets. Sometimes they experience 'Bichon Blitz' (zoomies)—sudden bursts of energy where they run around the house at top speed. While they are independent enough to tolerate some alone time, extended isolation can lead to separation anxiety.",
        "health": "Like Poodles, their curly double coat sheds very little but requires meticulous daily brushing to prevent severe matting, and professional grooming is a must. They are somewhat prone to allergies, which can manifest as skin issues or tear staining. Dental health is also a concern, so regular teeth brushing is necessary. Additionally, keeping an eye on their knees for patellar luxation is important."
    },
    5: {
        "history": "The Welsh Corgi originated in Wales, UK, where they were bred as herding dogs to drive cattle and sheep. Their uniquely short legs and long bodies allowed them to easily nip at the heels of cattle while smoothly dodging their kicks. They are famously known as the beloved breed of Queen Elizabeth II, who owned over 30 Corgis during her reign. Today, they are cherished worldwide for their distinctive 'loaf of bread' appearance and charming behinds.",
        "personality": "Corgis are highly intelligent, energetic, and alert. Due to their herding instincts, they may try to 'herd' running children or other pets by nipping at their heels, a behavior that requires early correction. They are very affectionate with their families but can be quite vocal, using their loud, deep bark to alert owners of strangers. They require a significant amount of daily exercise to burn off their boundless energy; without it, they can become bored and destructive.",
        "health": "Their long backs and short legs make them highly susceptible to Intervertebral Disc Disease (IVDD). It is crucial to prevent them from jumping off furniture, using stairs excessively, or becoming overweight, as obesity puts immense strain on their spine. Corgis are also heavy shedders, blowing their double coat twice a year, requiring frequent brushing to manage the shedding."
    },
    6: {
        "history": "The Chihuahua is the smallest recognized dog breed in the world, named after the Mexican state of Chihuahua. Their lineage is believed to trace back to the Techichi, a companion dog favored by the ancient Toltec civilization of Mexico. These tiny dogs were revered and even believed to guide the souls of the dead to the underworld. They were later brought to the US in the late 19th century, where their popularity skyrocketed due to their incredibly compact size.",
        "personality": "Chihuahuas are fiercely loyal to a single person and can become highly protective of their chosen owner. Despite their fragile size, they possess a surprisingly bold and feisty terrier-like attitude. They are highly alert and suspicious of strangers, making them excellent, albeit noisy, watchdogs. Because they are often babied due to their size, they can easily develop 'Small Dog Syndrome,' becoming bossy and aggressive if boundaries are not firmly established.",
        "health": "Their tiny jaws mean their teeth are crowded, making them highly prone to dental disease; daily brushing is mandatory. Many Chihuahuas are born with a 'molera' (a soft spot on the skull that may not fully close), requiring care to prevent head injuries. They are very sensitive to cold and often shiver, so sweaters in chilly weather are necessary. Tracheal collapse and patellar luxation are also common concerns."
    },
    7: {
        "history": "The Shih Tzu, meaning 'Lion Dog' in Chinese, was bred in the palaces of China by crossing the Pekingese and the Lhasa Apso. For centuries, they lived luxurious lives as the exclusive companions of Chinese emperors and royalty. They were highly prized and kept strictly within the palace walls. It wasn't until the 1930s that they were introduced to Europe, where their gentle nature and beautiful flowing coats quickly won hearts worldwide.",
        "personality": "Bred solely for companionship, the Shih Tzu is incredibly sweet, easygoing, and affectionate. They are known for their calm demeanor and are often content to simply lounge on the sofa beside their owner. They are generally friendly toward strangers and get along well with children and other pets. While they are intelligent, they can also be notoriously stubborn, making training a test of patience that requires positive reinforcement and high-value treats.",
        "health": "As a brachycephalic (flat-faced) breed, they are highly sensitive to heat and prone to respiratory issues; exercise in hot weather should be strictly avoided. Their prominent, large eyes are susceptible to injuries, ulcers, and dry eye, requiring daily monitoring and cleaning. Dental issues are also common due to their short jaws. Their long coat requires significant maintenance if kept long, though many owners opt for a shorter 'puppy cut' for easier care."
    },
    8: {
        "history": "The Golden Retriever was developed in Scotland in the mid-19th century by Lord Tweedmouth. He aimed to breed the ultimate retriever for hunting waterfowl, crossing the Yellow Retriever with the now-extinct Tweed Water Spaniel. The result was a dog with a superb nose, a 'soft mouth' (able to retrieve game without damaging it), and an unparalleled eagerness to please. Today, they are not only beloved family pets but also excel as search-and-rescue dogs, guide dogs, and therapy dogs.",
        "personality": "Golden Retrievers are famous for their incredibly friendly, tolerant, and gentle nature. They are notoriously poor watchdogs because they are more likely to greet a burglar with a wagging tail and a toy. They are highly intelligent, eager to please, and deeply devoted to their families, making them highly trainable. They retain a puppy-like playfulness well into adulthood and love having a 'job' to do, especially if it involves retrieving items or swimming.",
        "health": "Unfortunately, Goldens are genetically prone to certain cancers (like hemangiosarcoma and lymphoma), which are the leading cause of death in the breed. They are also susceptible to hip and elbow dysplasia, so maintaining a healthy weight and avoiding over-exercising them as puppies is crucial. Their dense, water-repellent double coat sheds continuously, with heavy blowouts twice a year, and they are prone to ear infections and skin allergies."
    },
    9: {
        "history": "The Jindo is an indigenous breed native to Jindo Island in South Korea. Isolated on the island for centuries, they developed naturally, retaining a pure lineage and strong survival instincts. They were historically used as hunting dogs for wild boars and deer. The Jindo is celebrated as a National Treasure (No. 53) in South Korea, highly revered for their legendary loyalty. A famous story tells of a Jindo named Baekgu, who was sold far away but traveled 300km back to her original owner.",
        "personality": "Jindos are fiercely loyal to their primary owner, often showing indifference or extreme wariness toward strangers. They are highly intelligent, independent, and possess a very high prey drive, meaning they may chase small animals. Because of their strong protective instincts and territorial nature, extensive early socialization is critical to prevent aggressive behaviors. They are remarkably clean dogs, often house-training themselves naturally and grooming themselves like cats.",
        "health": "The Jindo is generally a very healthy and robust breed with few genetic diseases, largely due to their natural development on the island. However, they can occasionally suffer from hypothyroidism and certain eye issues. Because they have a thick double coat to survive harsh winters, they shed profusely, especially during seasonal changes, requiring frequent brushing to remove dead undercoat."
    },
    10: {
        "history": "The Maltipoo is a popular 'designer dog' created by crossing a Maltese and a Toy or Miniature Poodle. Originating in the United States over the last few decades, the goal was to combine the highly affectionate nature and silky white coat of the Maltese with the high intelligence and non-shedding coat of the Poodle. As a mixed breed, they are not officially recognized by major kennel clubs, but their charming teddy-bear looks and excellent temperaments have made them incredibly sought after globally.",
        "personality": "Maltipoos generally inherit the best traits of both parent breeds. They are exceptionally loving, gentle, and thrive on constant human companionship. Their high intelligence from the Poodle side makes them quick learners and easy to train, while their Maltese heritage gives them a sweet, playful charm. However, their intense attachment to their owners means they are highly prone to separation anxiety if left alone for long periods. They are also known to be quite vocal, making them good alert dogs.",
        "health": "While crossing two breeds can sometimes increase overall health (hybrid vigor), Maltipoos can still inherit issues common to both the Maltese and the Poodle. Patellar luxation (slipping kneecaps) is the most common concern. They are also prone to dental disease, tear staining, and allergies. Their coat, which can range from wavy to curly, requires daily brushing to prevent mats and regular professional grooming."
    }
};

const data = JSON.parse(fs.readFileSync('breeds_data.json', 'utf8'));

data.forEach(item => {
    item.en = breedsEn[item.id];
    item.breedNameEn = breedsEn[item.id].breedNameEn || item.breedNameEn; // Just in case, though name might already be there
});

fs.writeFileSync('breeds_data.json', JSON.stringify(data, null, 4), 'utf8');
console.log('breeds_data.json translated.');
